### Bishop’s University

### CS 509 – Pattern Recognition

### Final project: Missing data

NAME: MABLINE ANDREA

STUDENT ID: 002351505

GROUP NAME: FP C

This final project aims to help you to understand the different methods to deal with missing
data. For that purpose, you will study two approaches. The first approach is imputation-
based approach. The principle is to assign replacement values to missing, invalid, or
inconsistent values. We can distinguish five methods related to imputation-based approach
that are the following:

• Imputation by a single value: default value, mean, median,

• Imputation by the center of the group,

• Imputation from the k nearest neighbors,

• Imputation by a partial mean,

• Imputation by singular value decomposition.

The second approach is based on EM algorithm which principle is to complete a series of
missing data based on the maximum likelihood of all the data.

With respect to the first approach that is the imputation-based approach, we can look into the 5 methods which is related to imputation based approach
1.The first one being imputation by a single value: which can be a default value, mean or a median.

### Imputation by a single value: default value, mean, median

### Using default value:
The missing values in a dataset can be replaced by default values such as 0 or unknown, this is one of the easier ways to tackle missing value, but also keeping in mind that bias can be introduced, it can create a pattern in the data that does not represent the true underlying distirbution, replacing with default values may not be the best option.


In [16]:
#Implementation using python

In [17]:
import pandas as pd
import numpy as np

#Creating a dataset with missing values 
data = {
    'Product': ['Tv', 'Phone', 'Washing-Machine', 'Head-phones', 'Keyboard'],  
    'Price': [2300, 560, np.nan, 800, np.nan],  
    'Rating': [4.5, 4.7, 4.2, np.nan, 4.8]  
}


df = pd.DataFrame(data)

print("Dataset consisting of missing values:")
print(df)


Dataset consisting of missing values:
           Product   Price  Rating
0               Tv  2300.0     4.5
1            Phone   560.0     4.7
2  Washing-Machine     NaN     4.2
3      Head-phones   800.0     NaN
4         Keyboard     NaN     4.8


In [18]:
df_default_values = df.fillna({'Price':0, 'Rating':0})

print('Imputation method using default values:')
print(df_default_values)

Imputation method using default values:
           Product   Price  Rating
0               Tv  2300.0     4.5
1            Phone   560.0     4.7
2  Washing-Machine     0.0     4.2
3      Head-phones   800.0     0.0
4         Keyboard     0.0     4.8


### Using mean value:

Next way is to replace the missing values using the mean value, the mean value is obtained by added all the values in that particular column and by divided the it with the total number of values in that column respectively, and this value can be used to replace all the missing values in that column.
This process can be performed for every other column that has missing values.

Cons:
Can introduce bias and not a good choice for complex data analysis. 

The formula to calculate the mean: Sum of all the individual data points/Total number of data points



Dataset:

Consider the numbers: (14, 23, 45, 67, 33, 22, 89, 54, 80, 98)
Let us calculate the mean:
The total number of values we have is 6 so n = 10

Let us sum all the numbers together:
Sum of the numbers: 14 + 23 + 45 + 67 + 33 + 22 + 89 + 54 + 80 + 98 = 525

The mean = Sum of all the values / Total number of values 
= 525/10 = 52.5



In [21]:
#Implementation using python

In [23]:
#Creating a dataset with missing values 
data = {
    'Product': ['Tv', 'Phone', 'Washing-Machine', 'Head-phones', 'Keyboard'],  
    'Price': [2300, 560, np.nan, 800, np.nan],  
    'Rating': [4.5, 4.7, 4.2, np.nan, 4.8]  
}


df = pd.DataFrame(data)

print("Dataset consisting of missing values:")
print(df)

df_mean = df.copy()
df_mean['Price'] = df_mean['Price'].fillna(df_mean['Price'].mean())
df_mean['Rating'] = df_mean['Rating'].fillna(df_mean['Rating'].mean())

print("Mean Value Imputation:")
print(df_mean)


Dataset consisting of missing values:
           Product   Price  Rating
0               Tv  2300.0     4.5
1            Phone   560.0     4.7
2  Washing-Machine     NaN     4.2
3      Head-phones   800.0     NaN
4         Keyboard     NaN     4.8
Mean Value Imputation:
           Product   Price  Rating
0               Tv  2300.0    4.50
1            Phone   560.0    4.70
2  Washing-Machine  1220.0    4.20
3      Head-phones   800.0    4.55
4         Keyboard  1220.0    4.80


### Using median value:

Next way to replace the missing values is by using the median value, the median value represeets the middle value, it is a measure of central tendency and is resistant to outliers especially in the case of skewed data distirbutions.

The formula to calculate the median is as follows:
The median is the middle value of the dataset, the median can be found by arranging all the values in ascending order and then splitting the values into two equal halves.

For odd number of values we can consider the middle value as the median.
For an even number of values : the median can be determined by dividing the middle two values by 2 and the resulting answer is the median.

Let us look at an example:
1.Odd Number of Values:(12, 34, 54, 13, 16)
First we arrange the numbers in the ascending order:
So the resulting values will be : (12, 13, 16, 34, 54)

In this case the middle value is 16 so the median here is 16.

2.Even number of values:(29, 17, 11, 09, 20, 10, 25, 30)
Firstly the values should be arranged in ascending order:
So the values even number of values in ascending order will be : (09, 10, 11, 17, 20, 25, 29, 30)

In this case the middle two values are : 17+20 = 37
so we divide 37/2 and the median is 18.5


In [25]:
#Creating a dataset with missing values 
data = {
    'Product': ['Tv', 'Phone', 'Washing-Machine', 'Head-phones', 'Keyboard'],  
    'Price': [2300, 560, np.nan, 800, np.nan],  
    'Rating': [4.5, 4.7, 4.2, np.nan, 4.8]  
}


df = pd.DataFrame(data)

print("Dataset consisting of missing values:")
print(df)

df_median = df.copy()
df_median['Price'] = df_median['Price'].fillna(df_median['Price'].median())
df_median['Rating'] = df_median['Rating'].fillna(df_median['Rating'].median())

print("Mean Value Imputation:")
print(df_median)


Dataset consisting of missing values:
           Product   Price  Rating
0               Tv  2300.0     4.5
1            Phone   560.0     4.7
2  Washing-Machine     NaN     4.2
3      Head-phones   800.0     NaN
4         Keyboard     NaN     4.8
Mean Value Imputation:
           Product   Price  Rating
0               Tv  2300.0     4.5
1            Phone   560.0     4.7
2  Washing-Machine   800.0     4.2
3      Head-phones   800.0     4.6
4         Keyboard   800.0     4.8


### • Imputation by the center of the group
With respect to imputation by center of the group, we can replace missing values in the dataset by making use of the ean, median or probably the mode value, and we can do this by grouping each category and estimating the details within each category respectively.

In [28]:
#Using the mean

In [1]:
import pandas as pd
import numpy as np

data = {
    'Stores': ['Costco', 'Costco', 'Best_Buy', 'Best_Buy', 'Maxi', 'Maxi', 'Walmart', 'Walmart'],
    'Product': ['Dishwasher', 'Table-Fan', 'Dishwasher', 'Table-Fan', 'Dishwasher', 'Table-Fan', 'Dishwasher', 'Table-Fan'],
    'Sales': [310, 250, np.nan, 390, 170, np.nan, 230, 175]
}
df = pd.DataFrame(data)

print("Original Dataset:")
print(df)

df['Stores'] = df['Stores'].str.lower()

group_mean = df.groupby('Stores')['Sales'].transform('mean')

print("\nMean Sales per Store:")
print(group_mean)


df['Sales'] = df['Sales'].fillna(group_mean)

print("\nDataset After Imputation:")
print(df)


Original Dataset:
     Stores     Product  Sales
0    Costco  Dishwasher  310.0
1    Costco   Table-Fan  250.0
2  Best_Buy  Dishwasher    NaN
3  Best_Buy   Table-Fan  390.0
4      Maxi  Dishwasher  170.0
5      Maxi   Table-Fan    NaN
6   Walmart  Dishwasher  230.0
7   Walmart   Table-Fan  175.0

Mean Sales per Store:
0    280.0
1    280.0
2    390.0
3    390.0
4    170.0
5    170.0
6    202.5
7    202.5
Name: Sales, dtype: float64

Dataset After Imputation:
     Stores     Product  Sales
0    costco  Dishwasher  310.0
1    costco   Table-Fan  250.0
2  best_buy  Dishwasher  390.0
3  best_buy   Table-Fan  390.0
4      maxi  Dishwasher  170.0
5      maxi   Table-Fan  170.0
6   walmart  Dishwasher  230.0
7   walmart   Table-Fan  175.0


In [2]:
#Using the median

import pandas as pd
import numpy as np


data = {
    'Stores': ['Costco', 'Costco', 'Best_Buy', 'Best_Buy', 'Maxi', 'Maxi', 'Walmart', 'Walmart'],
    'Product': ['Dishwasher', 'Table-Fan', 'Dishwasher', 'Table-Fan', 'Dishwasher', 'Table-Fan', 'Dishwasher', 'Table-Fan'],
    'Sales': [310, 250, np.nan, 390, 170, np.nan, 230, 175]
}
df = pd.DataFrame(data)

print("Original Dataset:")
print(df)


df['Stores'] = df['Stores'].str.lower()

group_median = df.groupby('Stores')['Sales'].transform('median')

print("\nMean Sales per Store:")
print(group_median)


df['Sales'] = df['Sales'].fillna(group_median)

print("\nDataset After Imputation:")
print(df)


Original Dataset:
     Stores     Product  Sales
0    Costco  Dishwasher  310.0
1    Costco   Table-Fan  250.0
2  Best_Buy  Dishwasher    NaN
3  Best_Buy   Table-Fan  390.0
4      Maxi  Dishwasher  170.0
5      Maxi   Table-Fan    NaN
6   Walmart  Dishwasher  230.0
7   Walmart   Table-Fan  175.0

Mean Sales per Store:
0    280.0
1    280.0
2    390.0
3    390.0
4    170.0
5    170.0
6    202.5
7    202.5
Name: Sales, dtype: float64

Dataset After Imputation:
     Stores     Product  Sales
0    costco  Dishwasher  310.0
1    costco   Table-Fan  250.0
2  best_buy  Dishwasher  390.0
3  best_buy   Table-Fan  390.0
4      maxi  Dishwasher  170.0
5      maxi   Table-Fan  170.0
6   walmart  Dishwasher  230.0
7   walmart   Table-Fan  175.0


### Imputation using K-Nearest Neighbor

KNN imputation replaces missing values in a dataset by considering the values of the closest data points. A distance metric, such as the Euclidean distance can be used to determine the similarity between data points. The missing value will then be replaced by the average (or weighted average) of the nearest neighbors corresponding values. Closer neighbors are given more importance as they are considered more similar to the data point with the missing value. Also keeping in mind that, KNN imputation is sensitive to the choice of k which is the number of neighbors and the distance metric used, which can affect the imputation results.

K-NN is a supervised machine learning algorithm that can be used for both classification and regression tasks.With respect to classification problems the class of the data point will be determined based on the majority vote among its k-nearest neigbors and for the regression problems the value of the missing data point will be determined based on the average of the values of its k-nearest neighbors.

KNN classification example:
Let us classify a new data point (5,2) into any one of the classes x1 or x2:

class x1: (2,3) (4,5) (7,8) 
class x2: (1,4) (2,8) (5,8) 
​
Let us choose k value that is the nearest neighbors value to be 3.
Let us calculate the distance to find thw 2 nearest neigbors from (5,2)

The distance metric is calculated using the Euclidean distance.


In [13]:
import numpy as np
from collections import Counter

x1 = [(2, 3), (4, 5), (7, 8)]
x2 = [(1, 4), (2, 8), (5, 8)]
data_point = (5, 2)

def euclidean_distance(p1, p2):
    return np.sqrt((p1[0] - p2[0])**2 + (p1[1] - p2[1])**2)

distances = []
for point in x1:
    distances.append((point, 'x1', euclidean_distance(data_point, point)))
for point in x2:
    distances.append((point, 'x2', euclidean_distance(data_point, point)))

distances.sort(key=lambda x: x[2])

k = 3
k_nearest_neighbors = distances[:k]

classes = [neighbor[1] for neighbor in k_nearest_neighbors]
predicted_class = Counter(classes).most_common(1)[0][0]

print("Data point:", data_point)
print("k Nearest Neighbors:", k_nearest_neighbors)
print("Predicted Class:", predicted_class)


Data point: (5, 2)
k Nearest Neighbors: [((2, 3), 'x1', 3.1622776601683795), ((4, 5), 'x1', 3.1622776601683795), ((1, 4), 'x2', 4.47213595499958)]
Predicted Class: x1


In [14]:
#Using the Imputation from the k nearest neighbors

In [44]:
import numpy as np
from sklearn.impute import KNNImputer

data = [
    [2.5, 1.6, 4.8],
    [6.5, np.nan, 2.3],
    [3.7, 5.0, 2.2],
    [6.0, 7.5, np.nan]
]

imputer = KNNImputer(n_neighbors=2, weights="distance")

imputed_data = imputer.fit_transform(data)

print("Original Data:")
print(np.array(data))
print("The imputed data where missing values are replaced:")
print(imputed_data)


Original Data:
[[2.5 1.6 4.8]
 [6.5 nan 2.3]
 [3.7 5.  2.2]
 [6.  7.5 nan]]
The imputed data where missing values are replaced:
[[2.5        1.6        4.8       ]
 [6.5        6.99620365 2.3       ]
 [3.7        5.         2.2       ]
 [6.         7.5        2.28277099]]


When weights is set to weights='distance' we use this so that closer neighbors will have more importance and similarity while considering them for the prediction.

### Imputation by a partial mean

With repect to partial mean here the missing values will be replaced by calculating the mean of the non-missing values in that particular column respectively and then that value will be used to replace the missing value only in that column.



In [45]:
import pandas as pd
import numpy as np

data = {
    "Feature 1": [2.7, 4.3, 5.5, 6.4],
    "Feature 2": [3.9, np.nan, 5.1, 7.2],
    "Feature 3": [1.1, 2.3, 3.8, np.nan]
}
df = pd.DataFrame(data)

for column in df.columns:
    df[column].fillna(df[column].mean(), inplace=True)
    
print("Imputed Dataset:")
print(df)


Imputed Dataset:
   Feature 1  Feature 2  Feature 3
0        2.7        3.9        1.1
1        4.3        5.4        2.3
2        5.5        5.1        3.8
3        6.4        7.2        2.4


C:\Users\Andrea\AppData\Local\Temp\ipykernel_10896\3608757844.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[column].fillna(df[column].mean(), inplace=True)


### Imputation by singular value decomposition

SVD that is singular value decomposition cane be used for reducing the dimensionality of thw dataset, as it helps in finding the most important or crucial features or patterns in a dataset. SVD will help in keeping only the most important patterns and thereby it will reconstruct the original data as a low-rank matrix, and this version will capture only the most important information without any other unnecessary information.

Let us look through the steps with respect to singular value decomposition:
 Our data is represented inthe form of a matrix and the columns represent our features or attributes and our rows represent our data value, SVD will break our matrix into three parts that is Σ: which represent the singular values, larger singular values represent the most important patterns and then there is U: which captures how the data points are related and then comes V^T which shows how the features are related so A=UΣV^T. Now only the top k singular values and vectors will be used to reconstruct the matrix. So the reconstructed matrix will help us in replacing the missing values in the original matix from the predicted values that we get through the reconstructed matrix, and this reconstructed matrix consists of the main core information about our data.
   




In [36]:
import numpy as np
from numpy.linalg import svd

data = np.array([
    [3.5, np.nan, 2.8],
    [2.6, 4.9, np.nan],
    [np.nan, 5.5, 6.7],
    [3.3, np.nan, 1.4]
])

def replace_nan_with_mean(data):
    column_means = np.nanmean(data, axis=0)
    data_replaced_with_mean = np.where(np.isnan(data), column_means, data)
    return data_replaced_with_mean

data_replaced_with_mean = replace_nan_with_mean(data)

U, Sigma, VT = svd(data_replaced_with_mean, full_matrices=False)

rank = 2
Sigma_reduced = np.diag(Sigma[:rank])  
U_reduced = U[:, :rank]
VT_reduced = VT[:rank, :]

data_reconstructed = np.dot(U_reduced, np.dot(Sigma_reduced, VT_reduced))

imputed_data = np.where(np.isnan(data), data_reconstructed, data)

print("Original data which consists of the missing values:")
print(data)
print("\nThe data after the mean imputation is performed:")
print(data_replaced_with_mean)
print("\nReconstructed Data having rank = 2:")
print(data_reconstructed)
print("\nFinal data after imputation:")
print(imputed_data)


Original data which consists of the missing values:
[[3.5 nan 2.8]
 [2.6 4.9 nan]
 [nan 5.5 6.7]
 [3.3 nan 1.4]]

The data after the mean imputation is performed:
[[3.5        5.2        2.8       ]
 [2.6        4.9        3.63333333]
 [3.13333333 5.5        6.7       ]
 [3.3        5.2        1.4       ]]

Reconstructed Data having rank = 2:
[[3.3118157  5.32654906 2.78172426]
 [2.8341647  4.74253031 3.65607451]
 [3.0749034  5.53929261 6.69432551]
 [3.34166687 5.17198011 1.40404653]]

Final data after imputation:
[[3.5        5.32654906 2.8       ]
 [2.6        4.9        3.65607451]
 [3.0749034  5.5        6.7       ]
 [3.3        5.17198011 1.4       ]]


### Using the EM algorithm

With respect to EM algorithm there are two steps:
1.The Expectation step (E) and 
2.Maximization step (M) 

In the Expectation step the missing values are estimated based on the observed data and the current parameters of the model.
Keeping the relationships, the correlation between variables, the predictions of missing values can be made, followed by the Maximization step where the parameters of the model need to be updated in order to maximize the likelihood of the data, including the predicted values for the missing values.
Then these two steps should be performed iteratively until convergence.

